apiVersion: apps/v1
kind: Deployment
metadata:
    name: ea-demo-project
spec:
  replicas: 1
  revisionHistoryLimit: 5 #imiting the number of old replicasets that Kubernetes keeps for rollback purposes
  selector:
    matchLabels:
      app: ea-demo-project
  strategy:
    rollingUpdate:
      maxSurge: 1 # as an absolute number of replicas
      maxUnavailable: 25% # as % of replicas
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ea-demo-project
    spec:
      containers:
        - name: ea-demo-project
          image: hadush/docker-kubernetes-ea-demo:v0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
#            requests:
#              cpu: "2"
#              memory: "2Gi"